language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"

# command to install dependencies
install: pip install $DJANGO --use-mirrors

# command to run tests
script: ./run_tests.sh

